stages:
  - build
  - test

image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -G "Ninja" -B build
    - cmake --build build --target all
  cache:
      paths:
        - build/

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - ctest --output-on-failure --test-dir build
