image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install ninja-build cmake
  script:
    - cmake -G "Ninja" -B build
    - cmake --build build --target all
  artifacts:
    paths:
      - build/ecpp_static_vector_ut
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  cache:
      paths:
        - build/

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt update && apt -y install cmake
  script:
    - ctest --output-on-failure --test-dir build
